/**
 * G1 evidence pass (P1-34).
 *
 * Runs the composed host and writes what a gate reviewer needs to judge it:
 * what eight contestants actually did and why, which scenes ran, and — kept
 * deliberately apart — the synthetic 136/137-actor counters that measure the
 * kernel rather than the game.
 *
 * Nothing here is estimated. Every number is produced by running something.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { core, host } from "../packages/sim/dist/index.js";

const SEED = 4107;
const OUT = "handoffs/P1-34/evidence";
mkdirSync(OUT, { recursive: true });

const lines = [];
const say = (text) => {
  lines.push(text);
};

say("=== G1 evidence — generated by tools/gen_g1_evidence.mjs ===");
say(`seed ${SEED}, host composed-1`);
say("");

// --- 1. What the eight contestants did, and why ------------------------------
const terrain = host.ComposedHost.create({ seed: SEED }).terrain;
const run = host.ComposedHost.create({ seed: SEED, terrain });
const before = run.summary().fullness;

const outcomes = new Map();
const traces = [];
for (let tick = 0; tick < 1200; tick += 1) {
  run.advance();
  for (const actor of run.actors) {
    const status = actor.lastStatus;
    if (status === undefined) continue;
    if (status.kind === "Completed" || status.kind === "Failed") {
      const key = `${actor.agent.actorId}:${status.kind}:${status.goalId}`;
      outcomes.set(key, (outcomes.get(key) ?? 0) + 1);
      if (traces.length < 8 && status.kind === "Completed") {
        traces.push(`    ${actor.agent.actorId} completed ${status.goalId} at tick ${tick}`);
      }
    }
  }
}
const after = run.summary().fullness;

say("1. Eight contestants, 1,200 ticks (two minutes of match time)");
say(`  fullness before: [${before.join(", ")}]`);
say(`  fullness after : [${after.join(", ")}]`);
say(`  living at the end: ${run.summary().living} of 8`);
say("  completed and failed goals, by actor:");
for (const key of [...outcomes.keys()].sort()) say(`    ${key} x${outcomes.get(key)}`);
say("  a sample of traced completions:");
for (const trace of traces) say(trace);

// A decision trace, so a reviewer can see the reasoning behind one choice.
const traced = core.decide(
  {
    actorId: "C001",
    traits: ["industrious"],
    evidence: [{ factId: 1, ageTicks: 20 }],
    candidates: [
      { candidateId: "goal.eat", considerations: [{ id: "hunger", inputMilli: 700, weightMilli: 1_000 }] },
      { candidateId: "goal.rest", considerations: [{ id: "fatigue", inputMilli: 200, weightMilli: 1_000 }] },
    ],
  },
  100,
);
say("  one decision trace, in full:");
say(`    chose ${traced.chosenCandidateId}, trigger ${traced.trace.trigger}`);
for (const candidate of traced.trace.candidates) {
  say(`      ${candidate.candidateId} = ${candidate.scoreMilli} (${candidate.considerations.map((c) => `${c.id} ${c.inputMilli}x${c.effectiveWeightMilli}=${c.contributionMilli}`).join(", ")})`);
}
say("");

// --- 2. Which G1 scenes execute ---------------------------------------------
say("2. G1-mapped scenes");
const scenes = [];
const clean = host.ComposedHost.create({ seed: SEED, terrain });
clean.runTicks(600);
scenes.push(["survival: hungry actors find and eat food", after.some((v, i) => v > before[i])]);
scenes.push(["world: the shipping island compiles and validates", terrain.manifest.island?.ok === true]);
scenes.push(["scene: the G1 window places starts, food and a camp", clean.knowledge.food.length > 0 && clean.knowledge.restSockets.length > 0]);
scenes.push(["time: a match reaches its first night", host.ComposedHost.create({ seed: SEED, terrain }).runTicks(5_200).isNight]);
const lawful = host.ComposedHost.create({
  seed: SEED,
  terrain,
  laws: [{ lawId: "law.truce", version: 1, permission: "SentientHarm", activationTick: 0, endTick: 10_000, scope: {}, reasonId: "WaitingForLaw" }],
});
lawful.runTicks(20);
scenes.push(["law: an installed truce denies sentient harm", lawful.permissions.check({ permission: "SentientHarm", tick: 10, actorPositionMm: [400_000, 400_000] }).verdict === "Denied"]);
scenes.push(["persistence: a save replays 600 identical ticks", host.replayDivergence(SEED, 120, 600, terrain) === null]);
for (const [label, ok] of scenes) say(`  ${ok ? "RUNS " : "FAILS"}  ${label}`);

say("");
say("  behaviours present in the full game and NOT exercised by this build:");
for (const missing of [
  "building: sockets are composed but no goal chooses to build",
  "combat: preparation, damage, revival and wildlife are composed but no goal chooses to fight",
  "perception: knowledge is supplied from the compiled scene, not earned through the sensory adapter",
  "society: clans, trust, teaching, promises and votes are P2 in their entirety",
  "economy: inventory transfers, ownership policy and reservations-for-items are unused by the goal library",
  "career: no career records are written (the Prototype8 profile sets writeCareer false)",
]) say(`    - ${missing}`);
say("");

// --- 3. Synthetic counters, kept separate ------------------------------------
say("3. Synthetic kernel counters — measured, and NOT evidence about the game");
const synthetic = host.SimHost.create({ matchSeed: SEED, withGuest: true });
const t0 = Date.now();
synthetic.runTicks(600);
const syntheticMs = Date.now() - t0;
say(`  W0-07 synthetic workload: 137 actors, 600 ticks in ${syntheticMs} ms, digest ${synthetic.authoritativeDigest()}`);
say(`  it declares ${core.WORKLOAD_OMISSIONS.length} omissions: ${core.WORKLOAD_OMISSIONS.join("; ")}`);
const t1 = Date.now();
host.ComposedHost.create({ seed: SEED, terrain }).runTicks(600);
say(`  composed host: 8 actors, 600 ticks in ${Date.now() - t1} ms — a different population and a different workload`);
say("  these two numbers are not comparable and neither is a rendering measurement;");
say("  GPU frame timing at 1920x1080 remains HUMAN_REQUIRED on reference hardware.");

writeFileSync(`${OUT}/g1-evidence.txt`, `${lines.join("\n")}\n`);
console.log(lines.join("\n"));
